name: Build and push to docker hub

on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
      - '**.gitignore'
      - '.github'

  workflow_dispatch:

jobs:
  docker:
    name: Push
    runs-on: ubuntu-latest

    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      with:
        platforms: 'linux/arm/v7,linux/arm64'

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.piwitten }}
        password: ${{ secrets.redred123 }}

    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        file: Dockerfile
        target: release
        platforms: linux/amd64,linux/arm/v7,linux/arm64
        push: true
        tags: ${{ secrets.piwitten}}/stb-proxy:latest
